version: "3"
services:
  spring:
    container_name: spring
    restart: always
    image: docker-image # cd.yml로 이미지 설정
    environment:
      SERVER_MODE: prod
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
      ORACLE_CLOUD_BUCKET: ${ORACLE_CLOUD_BUCKET}
      ORACLE_CLOUD_NAMESPACE: ${ORACLE_CLOUD_NAMESPACE}
    volumes:
      - ~/oracle-cloud-config:/oracle-cloud-config
      - ~/oracle-cloud-private.pem:/oracle-cloud-private.pem
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - nginx
    networks:
      - oreo

  mongo:
    container_name: mongo
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=oreo
    restart: always
    ports:
      - "27017:27017"
    command: [ --auth ]
    volumes:
      - ~/mongo:/data/db
    networks:
      - oreo

  nginx:
    container_name: nginx
    image: nginx:1.25.0-alpine
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443"
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/nginx/conf.d/application.conf:/etc/nginx/conf.d/application.conf
      - ~/build:/build
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    environment:
      - TZ=Asia/Seoul
    networks:
      - oreo

networks:
  oreo:
    external: true