version: "3"
services:
  spring:
    container_name: spring
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_MODE: local
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=oreo
    restart: always
    ports:
      - "27017:27017"
    command: [--auth]
    volumes:
      - ../mongo:/data/db