spring:
  profiles:
    default: "local"
    group:
      local:
        - "local"
        - "secret"
  servlet:
    multipart:
      max-file-size: 50000KB
      max-request-size: 50000KB
logging:
  exception-conversion-word: '%wEx'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}){green} %clr([%22thread]){magenta} %clr(%-40.40logger{39}){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  level:
    web: debug
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
---
spring:
  config:
    activate:
      on-profile: "local"
  origin: http://localhost
---
spring:
  config:
    activate:
      on-profile: "prod"
  origin: http://132.145.87.252