spring:
  profiles:
    default: "local"
    group:
      local:
        - "local"
        - "secret"
  servlet:
    multipart:
      max-file-size: 100000KB
logging:
  exception-conversion-word: '%wEx'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}){green} %clr([%22thread]){magenta} %clr(%-40.40logger{39}){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  level:
    web: debug
---
spring:
  config:
    activate:
      on-profile: "local"
